### ISSUE TITLE
1.1.0RC1 has ruby/server/ directory

### ISSUE THREAD

**Issue by kou** [roma/roma#30]
roma-1.1.0RC1.tar.gz has both `lib/` and `ruby/server/lib/` directory. It seems that ROMA migrated to `lib/` from `ruby/server/lib/` by #26. But the archive has `ruby/server/lib`.

And Groonga storage exists only `ruby/server/lib/`. Could you confirm it?

**Comment by banrui** [comment]
Thank you for your confirmation. We would like to confirm it.

**Comment by banrui** [comment]
We have completed this issue and release v1.1.0RC2 version.
Thank you.

**Comment by kou** [comment]
Thanks!
I've confirmed RC2.
