### ISSUE TITLE
Add "--replication-in-host" option to rename "--enabled_repeathost" to "--replication-in-host"

### ISSUE THREAD

**Issue by tarr1124** [roma/roma#33]
"--enabled_repeathost" option is making confusion now. We will rename "--enabled_repeathost" to "--replication-in-host" in the long term, so I add "--replication-in-host" option at first.
This option has same function of "--enabled_repeathost". 
We will remain the "--enabled_repeathost" option in the short term.

**Comment by banrui** [comment]
I have merged your pull request "https://github.com/roma/roma/pull/34".
