### ISSUE TITLE
[plugin]plugin_gui.rb does not resolve routing directory.

### ISSUE THREAD

**Issue by banrui** [roma/roma#38]
I think plugin_gui.rb does not resolve routing directory when there is other file and directory under routing direcotry.

```bash
bash$ ls -la /your/path/app/routing
192.168.xxx.xxx_10001.route
192.168.xxx.xxx_10001.route.1
192.168.xxx.xxx_10001.route.2
192.168.xxx.xxx_10002.route
192.168.xxx.xxx_10002.route.1
192.168.xxx.xxx_10002.route.2
hoge_direcotry ## this is bad directory.
```
If there is "hoge_direcotry" under your routing path, Gladiator does not work well.
Gladiator is ROMA GUI.
https://github.com/roma/gladiator

**Comment by hiroaki-iwase** [comment]
We modified it behavior on below commit.
https://github.com/roma/roma/commit/a4533a89d6ef64c79001b4efc5b1a9e803487a27
And this modification will be included in v1.1.0 release.

So I will close this issue.
