### ISSUE TITLE
Add 'groonga' option to mkconfig

### ISSUE THREAD

**Issue by assam212** [roma/roma#55]
Currently, mkconfig.rb has 2 storage options (RubyHash and TokyoCabinet).
ROMA v1.1.0 can use 'groonga' as storage software.
So mkconfig needs to add groonga option.

**Comment by hiroaki-iwase** [comment]
I added groonga storage option in mkconfig script and resove duplicate prob.
https://github.com/roma/roma/pull/77

**Comment by hiroaki-iwase** [comment]
I developed and merged.
https://github.com/roma/roma/commit/1011dea751cb3dd9319642eedbf53e9a3a864dfe

So I will close it.
