### ISSUE TITLE
Is there any release plan or milestone for the next release? 

### ISSUE THREAD

**Issue by satoryu** [roma/roma#83]
I've received many notifications from merging PRs and closing issues. 
But I could not understand where roma is moving ahead since many PRs don't have description. 

I think release plan or milestone for the next release would help users understand its direction roma is moving ahead.

**Comment by hiroaki-iwase** [comment]
Thanks for your advice!
Now release plan is just internal plan, so I will make it and mile stone for the next release.

Thanks again.

**Comment by hiroaki-iwase** [comment]
I made milestone on git.
Please check it.

And welcome your comment or additional request!

Thanks.
